dist: trusty
sudo: required
language: node_js
node_js:
  - 10

services:
  - postgresql

env:
  global:
    - PGUSER=postgres
    - PGPORT=5432

cache:
  directories:
  - node_modules

before_script:
  - psql -c 'create database weightdb;' -U $PGUSER
  - psql -c "CREATE USER dbuser WITH PASSWORD 'pa88w0rd';" -U $PGUSER
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE weightdb TO dbuser;" -U $PGUSER
  - npm install
  - npm install --only=dev
  - mv .env.template .env
  - npm run dev &
  - sleep 10

script:
  - npm test
