CREATE DATABASE IF NOT EXISTS WEIGHTDB;
DROP TABLE IF EXISTS WEIGHT_LOG;
CREATE TABLE IF NOT EXISTS WEIGHT_LOG (
  ID int(11) NOT NULL AUTO_INCREMENT,
  DATE date NOT NULL,
  WEIGHT double NOT NULL,
  PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS VIEW_WEIGHT;
CREATE VIEW VIEW_WEIGHT as SELECT DATE,WEIGHT FROM WEIGHT_LOG order by DATE DESC;
DROP TABLE IF EXISTS VIEW_WEIGHT_AVG;
CREATE VIEW VIEW_WEIGHT_AVG AS SELECT AVG(WEIGHT_LOG.WEIGHT) AS AVG FROM WEIGHT_LOG;