CREATE USER dbuser ENCRYPTED PASSWORD 'pa88w0rd' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE weightdb WITH OWNER dbuser;
GRANT ALL PRIVILEGES ON DATABASE weightdb TO dbuser;
\c weightdb;
CREATE TABLE IF NOT EXISTS weight_log(id SERIAL PRIMARY KEY, date DATE NOT NULL DEFAULT CURRENT_DATE, weight NUMERIC(4,1) NOT NULL );